[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "CloudHarvestCoreTasks"
version = "0.1.0"
description = "This is the Core Task system for CloudHarvest."
authors = [{name = "Cloud Harvest"}, {name = "Fiona June Leathers"}]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/Cloud-Harvest/CloudHarvestCoreTasks"
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.12",
]

[project.urls]
Source = "https://github.com/Cloud-Harvest/CloudHarvestCoreTasks"

[project.scripts]

[project.dependencies]
Jinja2 = "*"
PyYAML = "*"
python-dateutil = "*"
setuptools = "*"

[project.dev-dependencies]